### PR TITLE
Add EKS node group CloudFormation

### PR DESCRIPTION
**Pull request by robszumski**
The CloudFormation sets up all of the required infrastructure to add a set of Nodes with Nitro Enclaves enabled and ready for Kubernetes.

It allows IAM access to the S3 bucket and KMS key that is used by the example No-Fly List app.

This PR also removes the proposed scheduler and device management. I don't think this is needed because the anti-affinity by node hostname + label query to select nitro nodes works really well. Cluster autoscalers should react to the pending nodes just fine.

### CODE REVIEW

**Comment by robszumski** [comment]
I included [129c4aa](https://github.com/edgebitio/enclaver/pull/113/commits/129c4aaca4230bb3d41d1ce6f7ce877bba61ed8a) in here because I believe that some AWS accounts can benefit from the IAM role used for EKS. Basically, it allows the requester to have access to fetch the objects that are either already public (encrypted S3 object) or protected by a PCR policy.

**Comment by russellhaering** [comment]
I still don't really get 129c4aa, but if it fixes the problem lets ship it now and sort it out later.

**Review by russellhaering — APPROVED** [review]
+1

**Comment by robszumski** [comment]
I am not an expert, and the error messages are so generic, but I think [it's this](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic-cross-account.html#policy-eval-cross-account):

> When you make a cross-account request, AWS performs two evaluations. AWS evaluates the request in the trusting account and the trusted account. For more information about how a request is evaluated within a single account, see [Determining whether a request is allowed or denied within an account](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html#policy-eval-denyallow). The request is allowed only if both evaluations return a decision of Allow.

**Pull request merged**
